### ISSUE TITLE
Install Jekyll

### ISSUE THREAD

**Issue by kvnol** [heavyncode/heavynco.de#1]

**Comment by bparreira17** [comment]
@kvnol Dei uma lida a respeito do Jekyll que é um gerador de código estáticos e achei no tableless um post sobre ele:
https://tableless.com.br/jekyll-servindo-sites-estaticos/

Adicionei o link ao trello, as informações do post estão corretas?
Irei realizar o procedimento de instalação do Jekyll ainda hoje!
++ @lhocihara

**Comment by kvnol** [comment]
@brunoperlopes Isso aí! Faz um clone desse repositório, vamos usar a branch [dev](https://github.com/heavyncode/heavynco.de/tree/dev) para desenvolver, depois fazemos merge para master.
