### ISSUE TITLE
Install Stylus

### ISSUE THREAD

**Issue by bparreira17** [heavyncode/heavynco.de#4]
@lhocihara como @kvnol  mencionou o Stylus é um pré-processador  bem bacana para escrevermos o css de forma modular.

Segue abaixo como realizar a instalação do Stylus:
Link1:
https://www.npmjs.com/package/stylus
Video:
https://www.youtube.com/watch?v=o0xr1JRZOb4

Segue um post para leitura complementar do stylus:
http://blog.da2k.com.br/2015/02/15/escrevendo-css-com-stylus/

Adicionando os links no repositório do trello.

**Comment by bparreira17** [comment]
@kvnol @lhocihara quando todos estiverem ok com a instalação irei fechar o issue!

**Comment by kvnol** [comment]
@brunoperlopes As issues não são sobre a instalação em nossas máquinas, mas sim no projeto do site.

Mas, de qualquer forma, pode manter a issue aberta vou instalar o plugin do Stylus no Jekyll.

**Comment by kvnol** [comment]
Usaremos Sass invés do Stylus.
